Good Morning, Everyone! 🌟

A very warm welcome to today’s session! I hope you’re all feeling energized and ready to dive into an exciting topic. 🎉 Today, we’re going to explore Linear Algebra Hands on—a fascinating concept that’s sure to spark your curiosity! 🤔✨

Let’s make this session as interactive as possible—feel free to ask questions, share your thoughts, and participate actively. 🗣️💡 I promise it’s going to be both informative and fun! Let’s get started! 🚀📚

In [ ]:
#matrix
#matrix operations----+,-,*,/ ---clear
#transpose----clear
#deter----clear
#inverse---clear
#adjoint
#rank---
#decomposition
#eigen values,eigen vectors


In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,4],[4,1]])

In [ ]:
A

array([[2, 4],
       [4, 1]])

In [ ]:
A+2

array([[4, 6],
       [6, 3]])

In [ ]:
A-3

array([[-1,  1],
       [ 1, -2]])

In [ ]:
A*5

array([[10, 20],
       [20,  5]])

In [ ]:
A/2

array([[1. , 2. ],
       [2. , 0.5]])

In [ ]:
B = np.array([[1,2],[3,4]])

In [ ]:
B

array([[1, 2],
       [3, 4]])

In [ ]:
A+B

array([[3, 6],
       [7, 5]])

In [ ]:
A-B

array([[ 1,  2],
       [ 1, -3]])

In [ ]:
A*B

array([[ 2,  8],
       [12,  4]])

In [ ]:
A/B

array([[2.        , 2.        ],
       [1.33333333, 0.25      ]])

In [ ]:
A

array([[2, 4],
       [4, 1]])

In [ ]:
C = np.array([[1,2,3],[4,5,6]])

In [ ]:
C

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A+C

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [ ]:
D = np.array([[1,2],[4,5],[4,9]])

In [ ]:
D

array([[1, 2],
       [4, 5],
       [4, 9]])

In [ ]:
A+D

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
#vector multiplications
#Dot product (multiply the matrices of vectors even with the disimilar shapes)
#cross product(directly multiply the vectors of same dimension)

In [ ]:
A1 = np.array([[1,2],[2,1]])
A2 = np.array([[1,1],[2,2]])

In [ ]:
A1

array([[1, 2],
       [2, 1]])

In [ ]:
A2

array([[1, 1],
       [2, 2]])

In [ ]:
#dot product

np.dot(A1,A2)

array([[5, 5],
       [4, 4]])

In [ ]:
A3= np.array([[1,2],[2,1],[2,1]])
A4 = np.array([[1,1],[2,2]])

In [ ]:
A1=np.array([[1,2],[1,3]])
A2=np.array([[1,2],[1,6],[9,10]])
np.dot(A2,A1)

array([[ 3,  8],
       [ 7, 20],
       [19, 48]])

In [ ]:
A3

array([[1, 2],
       [2, 1],
       [2, 1]])

In [ ]:
A4

array([[1, 1, 8],
       [2, 2, 3]])

In [ ]:
np.dot(A3,A4)

array([[ 5,  5, 14],
       [ 4,  4, 19],
       [ 4,  4, 19]])

In [ ]:
#cross product

v1 = np.array([1,2,3])
v2 = np.array([[3,2,2],[3,6,9]])

In [ ]:
v1

array([1, 2, 3])

In [ ]:
v2

array([[3, 2, 2],
       [3, 6, 9]])

In [ ]:
np.cross(v1,v2)

array([[-2,  7, -4],
       [ 0,  0,  0]])

#transpose
#deter
#inverse
#adjoint
#rank
#decomposition
#eigen values,eigen vectors

In [ ]:
A

array([[2, 4],
       [4, 1]])

In [ ]:
A.T

array([[2, 4],
       [4, 1]])

In [ ]:
A1

array([[1, 2],
       [1, 3]])

In [ ]:
A1.T

array([[1, 1],
       [2, 3]])

In [ ]:
X = (A1.T).T

In [ ]:
X

array([[1, 2],
       [1, 3]])

In [ ]:
#det

A= np.array([[1,2,1],[1,2,2],[1,3,3]])

In [ ]:
A

array([[1, 2, 1],
       [1, 2, 2],
       [1, 3, 3]])

In [ ]:
np.linalg.det(A)

np.float64(-1.0)

In [ ]:
#random.randint

A= np.random.randint(1,5,(3,3))

In [ ]:
A

array([[4, 3, 2],
       [4, 1, 1],
       [3, 2, 3]])

In [ ]:
#inv

np.linalg.inv(A)

array([[-0.07692308,  0.38461538, -0.07692308],
       [ 0.69230769, -0.46153846, -0.30769231],
       [-0.38461538, -0.07692308,  0.61538462]])

In [ ]:
#rank

A

array([[4, 3, 2],
       [4, 1, 1],
       [3, 2, 3]])

In [ ]:
np.linalg.matrix_rank(A)

np.int64(3)

In [ ]:
x= np.array([[1,2,3],[5,6,7],[2,4,6]])

In [ ]:
np.linalg.matrix_rank(x)

np.int64(2)

In [ ]:
import numpy as np

In [ ]:
x= np.array([[1,2,3],[5,6,7],[2,4,6]])

In [ ]:
np.linalg.matrix_rank(x)

np.int64(2)

In [ ]:
#LU

from scipy.linalg import lu

G = np.array([[4,3],[6,3]])

P,L,U = lu(G)
print(P)
print(L)
print(U)

[[0. 1.]
 [1. 0.]]
[[1.         0.        ]
 [0.66666667 1.        ]]
[[6. 3.]
 [0. 1.]]


In [ ]:
#QR

from scipy.linalg import qr

G = np.array([[4,3],[6,3]])

Q,R = qr(G)

print(Q)
print(R)

[[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]
[[-7.21110255 -4.16025147]
 [ 0.         -0.83205029]]


In [ ]:
#cholesky

A= np.array([[4,2],[2,3]])

L= np.linalg.cholesky(A)

In [ ]:
L

array([[2.        , 0.        ],
       [1.        , 1.41421356]])

In [ ]:
L.T

array([[2.        , 1.        ],
       [0.        , 1.41421356]])

In [ ]:
#eigen values & eigen vectors

from numpy.linalg import eig

H = np.array([[5,4],[2,3]])

eigenvalues,eigenvectors = eig(H)

In [ ]:
eigenvalues

array([7., 1.])

In [ ]:
eigenvectors

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])