Create a numpy array with numpy.array module and with a data type integer and float.

In [ ]:
import numpy as np

In [ ]:
arr_int=np.array([1,2,3,4,5],dtype='int')
print(arr_int,type(arr_int))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
arr_float=np.array([1,2,3,4,5],dtype='float')
print(arr_float,type(arr_float))

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [ ]:
type(arr_float[1])

numpy.float64

Create numpy arrays that have zero, one, two, three, four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above. constraint: every array should contain atleast 5 elements

In [ ]:
arr0=np.array(8)
arr0,arr0.ndim

(array(8), 0)

In [ ]:
arr1=np.array([8,6,89,10,11])
arr1,arr1.ndim

(array([ 8,  6, 89, 10, 11]), 1)

In [ ]:
arr2=np.array([[8,6,89,10,11]])
arr2,arr2.ndim

(array([[ 8,  6, 89, 10, 11]]), 2)

In [ ]:
arr3=np.array([[[8,6,89,10,11]]])
arr3,arr3.shape

(array([[[ 8,  6, 89, 10, 11]]]), (1, 1, 5))

In [ ]:
arr4=np.array([[[[8,6,89,10,11]]]])
arr4,arr4.ndim

(array([[[[ 8,  6, 89, 10, 11]]]]), 4)

In [ ]:
arr4.shape

(1, 1, 1, 5)

In [ ]:
arr4=np.array([[[[8,6,89,10,11]]]])
arr4=arr4.flatten()
arr4,arr4.ndim

(array([ 8,  6, 89, 10, 11]), 1)

In [ ]:
# arr1=np.array([8,6,89,10,11],ndmin=64)
# arr1,arr1.ndim
# ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=64)

Create a 2x2, 3x3, and 4x4 identity matrix using numpy.  constraints use eye, idententiy

In [ ]:
arr=np.identity(2,dtype='int')
arr

array([[1, 0],
       [0, 1]])

In [ ]:
arr=np.identity(3,dtype='int')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
arr=np.identity(4,dtype='int')
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
arr=np.eye(2,2,dtype='int')
arr

array([[1, 0],
       [0, 1]])

In [ ]:
arr=np.eye(3,3,dtype='int')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
arr=np.eye(4,4,dtype='int')
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
arr=np.eye(2,3,dtype='int')
arr

array([[1, 0, 0],
       [0, 1, 0]])

Create a numpy array with shape 2x5 that has all the elements as zero.

In [ ]:
arr=np.zeros([2,5])
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr=np.eye(2,5)*0
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create a numpy array that has the shape 3x5 and all the elements are 5.

In [ ]:
arr=np.full([3,5],5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
arr=np.zeros([3,5],dtype='int')+5
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
arr=np.ones([3,5],dtype='int')+4
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
arr=np.eye(3,5,dtype='int')*0+5
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
arr=np.ones([3,5],dtype='int')
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# np.matrix([[]])

Create a numpy array with random integers in the range 0-100, and the sample size should be 25.

In [ ]:
arr=np.random.randint(0,100,size=25)
arr

array([ 5, 30, 42, 72, 43, 78, 32, 57, 16, 46, 85,  1, 76, 62, 78, 22, 32,
       83, 33, 30, 46, 37, 62, 76, 17])

In [ ]:
arr=np.random.randint(0,100,size=25)
arr

array([37, 90, 36, 95, 37, 34, 36, 74, 26, 81, 67, 11, 47, 77, 23,  2,  5,
       31, 50, 39, 74, 44, 47, 49, 78])

In [ ]:
arr=np.random.uniform(0,100,size=25)
arr

array([54.59014629, 91.49822503, 70.35598995,  2.2347478 , 37.16975908,
        8.75559367, 72.63070929, 31.56675376, 13.94605507, 38.59029518,
       90.51480427, 38.27219672, 77.81519411,  9.84292595,  9.14696032,
        5.88454178, 71.59378785, 85.10030117, 71.80249104, 15.09916491,
       49.81638089, 66.32636672, 66.74554256, 33.86425868, 69.43886525])

Create a numpy array in the shape 2x3 with random integers in the range 0-100. Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [ ]:
arr=np.random.randint(0,100,size=(2,3))
arr

array([[16,  4, 72],
       [18, 98, 44]])

In [ ]:
arr.reshape(3,2)


array([[16,  4],
       [72, 18],
       [98, 44]])

Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the following operations on the same.

a. Print the first ten elements of the array.

b. Print the last ten elements of the array.

c. Print the elements from the indexes 10-25.

d. Print the element at the index 22.

e. Print the array using negative indexing.

f. Print the last ten elements of the array, using negative indexing.

In [ ]:
arr=np.random.randint(0,1000,size=50)
arr

array([839, 103,   7,  71, 368, 264, 157,  35, 276,  72, 812,  90,  87,
        57, 463, 228,  12, 164, 838, 809, 614, 803, 612, 197, 774, 822,
       343, 450, 391, 190, 757, 317, 424, 451, 395, 369, 597, 760, 635,
        49,  66, 287, 564, 456,  38, 459, 893,  64, 122, 349])

In [ ]:
# a
arr[0:10]

array([839, 103,   7,  71, 368, 264, 157,  35, 276,  72])

In [ ]:
arr[40:]

array([ 66, 287, 564, 456,  38, 459, 893,  64, 122, 349])

In [ ]:
arr[-10:]

array([ 66, 287, 564, 456,  38, 459, 893,  64, 122, 349])

In [ ]:
arr[10:26]  #arr[start:end+1]

array([812,  90,  87,  57, 463, 228,  12, 164, 838, 809, 614, 803, 612,
       197, 774, 822])

In [ ]:
arr[22]

np.int64(612)

In [ ]:
arr[::-1]

array([349, 122,  64, 893, 459,  38, 456, 564, 287,  66,  49, 635, 760,
       597, 369, 395, 451, 424, 317, 757, 190, 391, 450, 343, 822, 774,
       197, 612, 803, 614, 809, 838, 164,  12, 228, 463,  57,  87,  90,
       812,  72, 276,  35, 157, 264, 368,  71,   7, 103, 839])

In [ ]:
arr[-10:]

array([ 66, 287, 564, 456,  38, 459, 893,  64, 122, 349])

In [ ]:
arr=np.zeros([3,5],dtype='int')+5
arr=arr.flatten()
arr,arr.ndim

(array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]), 1)

In [ ]:
ls=[4,5,6]
ls.pop()
ls

[4, 5]