In [1]:
import numpy as np
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
# 10 11 
# 14 15

In [2]:
ar1[2:4, 1:3]

array([[10, 11],
       [14, 15]])

In [ ]:
# if either start / end value is not given python automatically picks 0 and last values as default

In [ ]:
# [9, 10, 11, 12],
# [13, 14, 15, 16],
# [17, 18, 19, 20],
# [21, 22, 23, 24]

In [4]:
ar1[2:6, 0:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [5]:
ar1[2:6,0:] # no end value is given so python considers from zero till last

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [6]:
ar1[2:,0:] # no end value is given so python considers from zero till last

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [9]:
ar1[2:,:] # no start/end value is given so python considers from startting till last

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [8]:
ar1[2:] # no end value is given so python considers from zero till last
# when no value given for columns --> It's supposed to return everything in columns

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [10]:
ar1[:,2:]# no end value is given so python considers from zero till last
# when no value given for rows --> It's supposed to return everything in rows

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])

In [14]:
ar1 = np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [12]:
ar1[2:,1:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
ar2 = ar1.reshape(6,4)
ar2[2:,1:]

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20],
       [22, 23, 24]])

In [ ]:
# shape : used when you wanted to check how many rows and columns are there in array
# reshape: used when converting one array shape into another one

#### Array Manipulation

In [17]:
ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[50,60],[70,80]])
ar2

array([[50, 60],
       [70, 80]])

In [18]:
ar1

array([[10, 20],
       [30, 40]])

In [20]:
np.concatenate([ar1,ar2], axis = 0) # combine two arrays on rows
# before ar1 , ar2 individually has only two rows in each 
# ar1 --> 2,2 
# ar2 --> 2,2 
# conca --> 4, 2

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [23]:
np.vstack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [24]:
np.row_stack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [22]:
np.concatenate([ar1,ar2], axis = 1) # combine two arrays on columns
# 2, 4

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [25]:
np.hstack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [26]:
np.column_stack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [27]:
ar3 = np.concatenate([ar1,ar2,ar1], axis = 1)
ar3 # creating dummy array

array([[10, 20, 50, 60, 10, 20],
       [30, 40, 70, 80, 30, 40]])

In [28]:
np.hsplit(ar3,3) # split your array into 3 equal portions

[array([[10, 20],
        [30, 40]]),
 array([[50, 60],
        [70, 80]]),
 array([[10, 20],
        [30, 40]])]

In [29]:
ar1 = np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [30]:
ar1.size

24

In [ ]:
# rows * columns == ar1.size

In [31]:
ar1.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
ar1.reshape(3,-1) # -1 indicates one parameter is unknows and asking python to replace it with suitable value 
# in one reshape only single -1 is possible 

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [33]:
ar1.reshape(-1,-1)

ValueError: can only specify one unknown dimension