Todays agenda
Introduction to numpy
create numpy
functions of numpy
array
types of array

# what is numpy

numpy is a numerical python and
it is a very powerful library in python for numerical computing
mainly useful for working on datasets and performing mathematical cal

In [ ]:
list - it helps in storing different types of data , heterogeneous
disadavanatge
it consumes large memory
computation time is very high
cant perform any arithmetic operators

In [ ]:
numpy introduces array
-store data which are of same data type
-homogenous data
-it consumes less memory
-compuatation time is less
-can perform arithmatic operators as well


In [ ]:
import numpy as np

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
#list is heterogenous
x = [1,"xyz",8.0,7]
print(x)

[1, 'xyz', 8.0, 7]


In [ ]:
#array is homogenous
import numpy as np
x = np.array([1,2,3,8.0,"yyy"])   # int,float,string - yyy -??
print(x)
print(x.dtype)

['1' '2' '3' '8.0' 'yyy']
<U32


In [ ]:
x = np.array([1,2,3])
print(x)
print(x.dtype)

[1 2 3]
int32


In [ ]:
# 1 - int---- 1.0 - float
3.5 - ???

In [ ]:
#create array
list
tuple

In [ ]:
#using list
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [ ]:
#using tuple
import numpy as np
x = np.array((1,2,3,4,5))
print(x)

[1 2 3 4 5]


types of array -
o dimension array
1 dimension array
2 dimension array
3 dimension array
n dimension array

In [ ]:
#o dimension
a = np.array(10)
print(a)
print(a.ndim)

10
0


In [ ]:
#1dimension
a = np.array([10,20,30,40,50])
print(a)
print(a.ndim)

[10 20 30 40 50]
1


In [ ]:
#2d
a =np.array([[10,20],[30,40]])
print(a)
print(a.ndim)

[[10 20]
 [30 40]]
2


In [ ]:
#3d
a = np.array([[[10,20],[30,50],[60,70],[80,90]]])
print(a)
print(a.ndim)

[[[10 20]
  [30 50]
  [60 70]
  [80 90]]]
3


In [ ]:
#indexing
list1 = [1,2,3,4,5,6,7,8]
a = np.array(list1)
a[-1]

8

In [ ]:
#Reshape function
#1d-2d
a = np.array([1,2,3,4,5,6])
b = a.reshape((3,2))  #6 elements - 2* 3, 3*2,6*1,1*6
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#2d -1d
a = np.array([[1,2],[3,4]])
b = a.reshape(-1)
print(b)

[1 2 3 4]


In [ ]:
#matrix operations using numpy
np.full() - will create a numpy array of n dimesions  and will fill it with one element completrely
np.zeros()- will fill with zeros
np.ones()- will fill with ones
np.identity() - will create a identity matrix of n*n size
np.eye() - will create m*n matrix

In [ ]:
a = np.full((2,3),7)
print(a)

[[7 7 7]
 [7 7 7]]


In [ ]:
a = np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
c = np.ones((4,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
d = np.identity(3)#n*n
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.eye(4,9)#m*n
print(e)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
#random functions in numpy
1.randint
2.random
3.linspace
4.arange

In [ ]:
#randint
x = np.random.randint(1,100)
print(x)

72


#training any data - 70%
testing -30%

100% data - 1-70 machine, 70-30 test
1-100 1-10,11-20,20-30

In [ ]:
y = np.random.random((2,3)) #0-1
print(y)

[[0.85388249 0.32838288 0.65014668]
 [0.34054268 0.87756375 0.82843194]]


In [ ]:
1000 marks
20 marks -a
950 - marks b
0-1

In [ ]:
z = np.linspace(0,5,num =15)
print(z)

[0.         0.35714286 0.71428571 1.07142857 1.42857143 1.78571429
 2.14285714 2.5        2.85714286 3.21428571 3.57142857 3.92857143
 4.28571429 4.64285714 5.        ]


In [ ]:
x = np.arange(0,10,2) #start,stop,step
print(x)

[0 2 4 6 8]


In [ ]:
#Arithmetic operators on arrays(+,-,*,/,//,%)
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
result = a+b
print(result)

[5 7 9]


In [ ]:
result = a-b
print(result)

[-3 -3 -3]


In [ ]:
result = a*b
print(result)

[ 4 10 18]


In [ ]:
result = a/b
print(result)

[0.25 0.4  0.5 ]


In [ ]:
result = a//b
print(result)

[0 0 0]


In [ ]:
result = a%b
print(result)

[1 2 3]


#broadcasting numpy
simple rule
2d array, 1d array
2d array

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
result = a+b
print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
result = a-b
print(result)

[[ -9 -18 -27]
 [ -6 -15 -24]]


In [ ]:
#sum
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
x = np.sum(a)
print(x)

21


In [ ]:
#along rows = axis =1
#along columns = axis =0
y =np.sum(a, axis = 1)
print(y)

[ 6 15]


In [ ]:
y =np.sum(a, axis = 0)
print(y)

[5 7 9]


In [ ]:
#np.mean
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) #1+2+3+4+5+6 = 21/6 = 3.5
x = np.mean(a)
print(x)

3.5


In [ ]:
y = np.mean(a,axis =1) #3+2+1 = 6 ---6/3----2
print(y)

[2. 5.]


In [ ]:
#np.std  --- mean (3.5 - 1)^2 2.5, 3.5 -2  = 255 =
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
x= np.std(a)
print(x)

1.707825127659933


---std #sqrt of variance =std

In [ ]:
#variance
np.var
a = np.array([[1,2,3],[4,5,6]])
x= np.var(a)
print(x)

2.9166666666666665


In [ ]:
#np.sqrt()
#np.exp()

In [ ]:
#np.sort
a = np.array([3,1,4,6,2,7,9,0,8])
x= np.sort(a)
print(x)

[0 1 2 3 4 6 7 8 9]


In [ ]:
#argsort- for knowing the index values
b = np.array([1,2,3,4])  #4,5,6,7,8 # 0,1,2,3,4
x = np.argsort(b)
print(x)

[0 1 2 3]


# Pandas

-powerfull and flexible open source data analysis and adata manipulation
-panel data- word came from
-easy handling
-manipulation of data structures
real life uses
retail sales analysis
-finance
-healthcare

-series
-data frame

In [ ]:
#series
-1d array
-hold any type of data
-homogenous
-very easy to access and manipulate tha data
-labeled data

In [ ]:
#data frame
data frame - 2d
-size is mutable
-heterogenous- multiple col - 1,2,3
-age, name,height- int,str,float
-tabular data structure with labeled axis(rows and columns)

In [ ]:
#how to create pandas
import pandas as pd

In [ ]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [ ]:
print(pd.__version__)

1.4.2


In [ ]:
import pandas as pd
#list
x = [10,20,30,40,50]
y = pd.Series(x)
print(y)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
a =  (10,20,30,40,50)#tuple
b = pd.Series(a)
print(b)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
a = {10,20,30,40,50} #set
b = pd.Series(list(a))
print(b)

0    50
1    20
2    40
3    10
4    30
dtype: int64


In [ ]:
#dic
x = {'a':10,'b':20,'c':30,'d':40}
y = pd.Series(x)
print(y)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
#data frame
x = [[1, 'john',30],[2,'kiwi',20],[3,'orange',35]]
y = pd.DataFrame(x,columns =['ID','Name','Age'])
print(y)
y['Gender'] = ['m','f','T']
print(y)
y = y.drop('Age',axis = 1)
print(y)
a = {'ID':4,'Name':'apple','Age':10}
y = y.append(a,ignore_index = True)
print(y)

   ID    Name  Age
0   1    john   30
1   2    kiwi   20
2   3  orange   35
   ID    Name  Age Gender
0   1    john   30      m
1   2    kiwi   20      f
2   3  orange   35      T
   ID    Name Gender
0   1    john      m
1   2    kiwi      f
2   3  orange      T
   ID    Name Gender   Age
0   1    john      m   NaN
1   2    kiwi      f   NaN
2   3  orange      T   NaN
3   4   apple    NaN  10.0


C:\Users\hp\AppData\Local\Temp\ipykernel_23736\3994745526.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y = y.append(a,ignore_index = True)


In [ ]:
#tuple
import pandas as pd
x = [(1, 'john',30),(2,'kiwi',20),(3,'orange',35)]
y = pd.DataFrame(x,columns =['ID','Name','Age'])
print(y)

   ID    Name  Age
0   1    john   30
1   2    kiwi   20
2   3  orange   35
