In [1]:
import numpy as np

In [3]:
ar1=np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [5]:
list=[1,2,3,4,5]
[i **2 for i in list]
ar1 ** 2

array([ 1,  4,  9, 16, 25])

In [7]:
ar1.dtype

dtype('int32')

In [11]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [15]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.random.random([3,2])

array([[0.35389212, 0.67120026],
       [0.29934751, 0.22782541],
       [0.28781801, 0.53750094]])

In [19]:
np.full([3,2],10)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [45]:
print(type(list))


<class 'list'>


In [47]:
del list


In [49]:
print(list(range(1, 5)))

[1, 2, 3, 4]


In [55]:
list(range(1,2,10))

[1]

In [59]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [61]:
np.linspace(1,20,11)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

In [65]:
ar2=np.arange(1,25)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [67]:
ar2.ndim

1

In [69]:
ar2.size

24

In [71]:
ar2.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [73]:
ar2=ar2.reshape(6,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [75]:
ar2.ndim

2

In [77]:
ar3=ar2.reshape(3,2,4)
ar3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [81]:
ar2.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.],
       [21., 22., 23., 24.]])

In [85]:
np.array([[10,20],[30,40]])

array([[10, 20],
       [30, 40]])

In [87]:
np.sum([[10,20],[30,40]])

100

In [89]:
np.sum([[10,20],[30,40]],axis=0)

array([40, 60])

In [91]:
np.sum([[10,20],[30,40]],axis=1)

array([30, 70])

In [105]:
np.array([[10, 20, 1], [30, 40, 2],  [50, 60, 3]])

array([[10, 20,  1],
       [30, 40,  2],
       [50, 60,  3]])

In [107]:
np.sum([[10,20,1],[30,40,2],[50,60,3]],axis=0)

array([ 90, 120,   6])

In [111]:
help(np.exp)

Help on ufunc:

exp = <ufunc 'exp'>
    exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Calculate the exponential of all elements in the input array.

    Parameters
    ----------
    x : array_like
        Input values.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``out=None

In [113]:
print(np.subtract(10,20))
print(np.multiply(10,20))
print(np.divide(10,20))
print(np.log(10))
print(np.exp(10))
print(np.sqrt(10))
print(np.sin(10))

-10
200
0.5
2.302585092994046
22026.465794806718
3.1622776601683795
-0.5440211108893698


In [117]:
ar1=np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [119]:
ar1[1:6,1:4]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20],
       [22, 23, 24]])

In [121]:
ar1[1:10,1:12]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20],
       [22, 23, 24]])

In [125]:
ar1[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20],
       [22, 23, 24]])

In [129]:
ar1[:1:]

array([[1, 2, 3, 4]])