In [1]:
import numpy # this package is already available so its not throwing an error

In [2]:
import xyz # random word used to explain this module not found error

ModuleNotFoundError: No module named 'xyz'

In [3]:
import Numpy

ModuleNotFoundError: No module named 'Numpy'

In [4]:
import numpyy

ModuleNotFoundError: No module named 'numpyy'

In [ ]:
ModuleNotFoundError: No module named 'xyz'
1. Case sensitive
2. Spelling mistake
3. Package is not available so we need to install it

In [5]:
!pip install numpy # right now numpy is already available so need not do this installation
# this if for future when faced with module not found error this is how you can solve it

In [6]:
import numpy

#### Create an array

In [8]:
ar1 = numpy.array([1,2,3,4,5]) # 
ar1

array([1, 2, 3, 4, 5])

In [9]:
type(ar1)

numpy.ndarray

In [10]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [11]:
list1[2] = 20 # element wise operations
list1

[1, 2, 20, 4, 5]

In [12]:
[i**2 for i in list1]

[1, 4, 400, 16, 25]

In [13]:
ar1 **2 

array([ 1,  4,  9, 16, 25])

In [16]:
ar1

array([1, 2, 3, 4, 5])

In [19]:
ar1

array([1, 2, 3, 4, 5])

In [21]:
ar2 = 1

In [22]:
ar2

1

In [ ]:
# NameError:
# 1. Case Sensitive 
# 2. Spelling mistake
# 3. Re create that variable which is throwing name error 

In [ ]:
# nameError : numpy is not defined ( execture import numpy line )

#### Creating Array

In [ ]:
import numpy

In [23]:
ar1 = numpy.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [24]:
import numpy as np # alias name called np 

In [25]:
ar1 = np.array([1,2,3,4,5]) # list / tuple and convert them into an array
ar1

array([1, 2, 3, 4, 5])

In [ ]:
# if you want to create an array with zeros use this function

In [26]:
ar1 = np.zeros([3,4]) # 1 parameters --> [3,4] --> shape --> rows and columns
# create an array of 3 rows and 4 columns and fill this array wth zeros 
# by default data type is float --> 0. --> 0 
ar1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# help(np.zeros)

In [ ]:
# to create a random array in a range of 0 to 1

In [37]:
np.random.random([3,4]) # shape --> [3,4] --> 3 rows and 4 columns and filled with random numbers 

array([[0.32653449, 0.91945953, 0.34892924, 0.95467864],
       [0.51279142, 0.08767312, 0.1472828 , 0.78811349],
       [0.96105437, 0.71687736, 0.03950883, 0.45911477]])

#### Initiating an array

In [38]:
np.full([3,4], 10)  # 2 parameters : shape , value
# create an array of size 3 rows and 4 columns and fill the array with value 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [40]:
for i in range(0,4):
    print(i)

0
1
2
3


In [41]:
list(range(0,4))

[0, 1, 2, 3]

In [42]:
list(range(0,10,2)) # start , end-1, step 

[0, 2, 4, 6, 8]

In [43]:
np.arange(0,10,2) # start , end-1(excluding end), step

array([0, 2, 4, 6, 8])

In [45]:
np.linspace(0,10,20) # start , end, no.of values to generate
# from 0 till 10 generate 5 numbers with equal intervals (difference)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
# # Attribute Error :
# 1. Case Sensitive 
# 2. Spelling mistake 
# 3. The functions doesnt exisit

#### Array Inspection

In [51]:
ar1 = np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [52]:
ar1.ndim

1

In [53]:
ar1.size # how many elements are there in ar1

24

In [ ]:
# ar1.size = rows* columns 
24
1*24 
2*12
3*8
4*6
6*4
..

In [54]:
ar1.reshape(6,4) 
# 6*4 = 24

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [55]:
ar1.reshape(5,5) 
# 5*5 != 24 ( size)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [56]:
ar1.reshape(4,4)
# 4*4 != 24

ValueError: cannot reshape array of size 24 into shape (4,4)

In [57]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [60]:
ar1.ndim

1

In [58]:
ar2 = ar1.reshape(6,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [59]:
ar2.ndim

2

In [64]:
ar3 = ar1.reshape(3,2,4) # create 3 sub matrix with size 2,4 
ar3.ndim

3

In [67]:
ar3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [66]:
ar4 = ar1.reshape(3,2,2,2)
ar4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])

In [68]:
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [69]:
ar1.size #no.of elements in array 

24

In [70]:
ar1.shape # rows, columns

(6, 4)

In [71]:
ar1.dtype # data type 
# 32 bits / 64 bits 
# numbers should be in integers

dtype('int32')

#### Array Mathematics

In [ ]:
ar1 = np.array([[10,20],[30,40]])
ar1

np.sum(ar1) # add all elements in array (10+20+30+40)

np.sum(ar1,axis = 0) # axis = 0 --> apply the sum function on rows

np.sum(ar1,axis = 1) # axis = 1 --> apply the sum function on columns

help(np.sum)

In [80]:
print(np.subtract(10,20))
print(np.multiply(10,20))
print(np.divide(10,20))
print(np.log(10))
print(np.exp(10))
print(np.sqrt(10))
print(np.sin(10))

-10
200
0.5
2.302585092994046
22026.465794806718
3.1622776601683795
-0.5440211108893698


In [84]:
ar1

array([[10, 20],
       [30, 40]])

In [85]:
np.min(ar1)

10

In [86]:
np.max(ar1)

40

In [88]:
np.mean(ar1) # average --> sum of the observations / total no.of obser
# (10+20+30+40)/4

25.0

In [89]:
np.median(ar1)

25.0

#### Slicing

In [ ]:
# Index will start with zero 
# end will be excluded ( end-1 )

In [90]:
ar1 = np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [91]:
ar1[0]

1

In [92]:
ar1[0:5] # 5 is not included

array([1, 2, 3, 4, 5])

In [93]:
# 2D data

In [94]:
ar2 = ar1.reshape(6,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [95]:
ar2[1:5,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])